"""multireport

Revision ID: 6bae8b053819
Revises: c381a7fd6f67
Create Date: 2019-09-18 14:13:06.186705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bae8b053819'
down_revision = 'c381a7fd6f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_model', sa.Column('cross_trail', sa.String(length=16), nullable=False))
    op.add_column('report_model', sa.Column('issues', sa.String(length=256), nullable=False))
    op.add_column('report_model', sa.Column('type', sa.String(length=32), nullable=False))
    op.drop_column('report_model', 'issue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_model', sa.Column('issue', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('report_model', 'type')
    op.drop_column('report_model', 'issues')
    op.drop_column('report_model', 'cross_trail')
    # ### end Alembic commands ###
