"""initial

Revision ID: c381a7fd6f67
Revises:
Create Date: 2019-09-17 17:57:31.025347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c381a7fd6f67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('issue', sa.String(length=128), nullable=False),
    sa.Column('reporter', sa.String(length=128), nullable=True),
    sa.Column('reporter_slack_handle', sa.String(length=64), nullable=True),
    sa.Column('reporter_slack_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.UnicodeText(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('gps', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('slack_file_id', sa.String(length=32), nullable=False),
    sa.Column('s3_url', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_model')
    op.drop_table('report_model')
    # ### end Alembic commands ###
